version: '3.8'

services:
  app:
    image: php:8.1-apache
    platform: linux/amd64
    container_name: codeigniter_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf  # Custom Apache config
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile # Ensure you have this Dockerfile in your project

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: cocdeigniter_db
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:

